### PR TITLE
Currently Available Providers had missing links

### PR DESCRIPTION
**Pull request by pranav767**
Prometheus, Elasticsearch and Grafana Loki hyperlinks were missing

### CODE REVIEW

**Review by gulshanpr — COMMENTED** [review]
hey @pranav767, the correction you have did is wrong, In the README file there is already mentioned about adding link in the correct format and you have not followed it. you should check the README and do it again.

**Comment by pranav767** [comment]
Hey @gulshanpr ,I get that we are using [linked text](doc:prometheus)
But in the actual docs page if I click on prometheus , it did'nt redirect me to that page of docs. I can't understand what the problem is can you have a look at it?

**Comment by pranav767** [comment]
I guess [prometheus](../prometheus) this would solve the problem as we are currently in notebooks.md so slug is notebooks 🤔

**Review by keturiosakys — CHANGES_REQUESTED** [review]
Hi! Thanks for catching these.

The correct format for links is: `[Link text](doc:<slug>)` (the current version has `docs` instead which is why the links won't work). 

If you can update your PR with the correct format, we can merge it.

**Comment by pranav767** [comment]
Thanks for pointing it out 😄 
I have made the changes can you review those @keturiosakys

**Review by keturiosakys — APPROVED** [review]

**Pull request merged**
